name: "dbt_equipment_losses"
version: "1.0.0"
config-version: 2

profile: "dbt_equipment_losses"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["data"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_equipment_losses:
    system_category:
      +materialized: view
    cumulative_losses:
      +materialized: view
    unknown_equipment:
      +materialized: view
    equipment_analysis:
      +materialized: table

seeds:
  dbt_equipment_losses:
    equipment_losses:
      +column_types:
        date_recorded: date
