dbt_equipment_losses:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: culley
      pass: ""
      port: 5432
      dbname: dbt_equipment_losses
      schema: public
      threads: 4
